In [643]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from docx import Document

In [644]:
document = Document("POs_and_COs.docx")

In [645]:
def read_docx_table(document,table_num):
  table = document.tables[table_num-1]
  data = [[cell.text for cell in row.cells] for row in table.rows]
  df = pd.DataFrame(data)
  return df

## PLO TABLE

In [ ]:
table_num=1
df = read_docx_table(document,table_num)
df.head()

     0                                                  1
0  PO1  Identify, select and apply appropriate knowled...
1  PO2  Understand, apply and integrate best practices...
2  PO3  Work collaboratively among members of the team...
3  PO4  Communicate effectively with users to identify...
4  PO5  Creatively design, implement and evaluate usin...

In [647]:
q1 = df.copy()

In [648]:
count_vectorizer = CountVectorizer(stop_words='english', min_df=0.005)

In [649]:
q1[1] = q1[1].str.lower()
corpus = q1[1].tolist()
corpii = count_vectorizer.fit_transform(corpus)

In [650]:
corpii

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 261 stored elements and shape (15, 176)>

In [651]:
feature_names = count_vectorizer.get_feature_names_out()
feature_names

array(['able', 'accomplishment', 'account', 'act', 'activities',
       'administration', 'agenda', 'aligned', 'analysis', 'analytical',
       'analyze', 'analyzing', 'applications', 'apply', 'applying',
       'appropriate', 'assess', 'assessing', 'assist', 'based', 'best',
       'clear', 'collaborative', 'collaboratively', 'communicate',
       'communities', 'community', 'competencies', 'complex',
       'components', 'computer', 'computing', 'consequential',
       'considering', 'constraints', 'contexts', 'contributing',
       'creation', 'creative', 'creatively', 'critical', 'cultural',
       'culture', 'current', 'decisions', 'define', 'demonstrate',
       'design', 'desired', 'developing', 'development', 'different',
       'diverse', 'diversity', 'economy', 'effective', 'effectively',
       'end', 'english', 'environment', 'equity', 'ethical', 'evaluate',
       'evaluates', 'evaluating', 'evaluation', 'expertise', 'field',
       'filipino', 'function', 'generation', 'global', 'goals',
       'graduates', 'health', 'identify', 'impact', 'implement',
       'individual', 'individuals', 'information', 'instructions',
       'integrate', 'interpersonal', 'interviewing', 'issues', 'justice',
       'knowledge', 'language', 'large', 'leader', 'leaders', 'learning',
       'legal', 'local', 'logical', 'making', 'mathematics', 'meet',
       'member', 'members', 'methods', 'multicultural',
       'multidisciplinary', 'national', 'necessary', 'needs', 'new',
       'organizations', 'participate', 'participation', 'plan',
       'policies', 'positively', 'possible', 'practice', 'practices',
       'practicing', 'presentations', 'problems', 'process', 'processes',
       'profession', 'professional', 'programs', 'project', 'projects',
       'promote', 'properly', 'quantitative', 'range', 'reasoning',
       'relevant', 'requirements', 'research', 'respectfully',
       'responsibilities', 'responsibility', 'responsibly', 'result',
       'safety', 'science', 'security', 'select', 'selection', 'sense',
       'settings', 'skills', 'social', 'societal', 'society', 'solution',
       'solutions', 'solving', 'standards', 'sufficient', 'systems',
       'team', 'teams', 'techniques', 'technology', 'theory', 'thinking',
       'tools', 'understand', 'understanding', 'use', 'user', 'users',
       'using', 'utilization', 'values', 'various', 'view', 'work',
       'writing'], dtype=object)

In [652]:
len(feature_names)

176

In [653]:
X1 = pd.DataFrame(corpii.toarray(), columns=feature_names)

## CLO TABLE

In [654]:
table_num=2
df1 = read_docx_table(document,table_num)
p1 = df1.copy()

In [655]:
p1[1] = p1[1].str.lower()
corpus11 = p1[1].tolist()
corpii11 = count_vectorizer.fit_transform(corpus11)

In [656]:
feature_names1 = count_vectorizer.get_feature_names_out()
feature_names1

array(['administer', 'administrative', 'allocated', 'configuration',
       'domains', 'effectively', 'formulate', 'governing', 'implement',
       'justify', 'maintain', 'measures', 'modify', 'operating',
       'organization', 'policies', 'policy', 'recommend', 'resources',
       'systems', 'use', 'various'], dtype=object)

In [657]:
len(feature_names1)

22

In [658]:
X2 = pd.DataFrame(corpii11.toarray(), columns=feature_names1)

In [659]:
X2.head()

,administer,administrative,allocated,configuration,domains,effectively,formulate,governing,implement,justify,...,modify,operating,organization,policies,policy,recommend,resources,systems,use,various
0,0,1,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
1,0,0,0,0,0,0,1,1,0,0,...,0,0,1,1,0,0,0,1,1,0
2,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
3,0,0,0,1,0,0,0,0,1,0,...,1,1,0,0,1,0,0,0,0,0

In [ ]:
U2 = pd.concat([df1[0], X2], axis=1)
U2.set_index(0, inplace=True)

In [661]:
U2.head()

,administer,administrative,allocated,configuration,domains,effectively,formulate,governing,implement,justify,...,modify,operating,organization,policies,policy,recommend,resources,systems,use,various
0,,,,,,,,,,,,,,,,,,,,,
CO1,0,1,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
CO2,0,0,0,0,0,0,1,1,0,0,...,0,0,1,1,0,0,0,1,1,0
CO3,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
CO4,0,0,0,1,0,0,0,0,1,0,...,1,1,0,0,1,0,0,0,0,0

In [662]:
U1 = pd.concat([df[0], X1], axis=1)
U1.set_index(0, inplace=True)

In [663]:
U1

,able,accomplishment,account,act,activities,administration,agenda,aligned,analysis,analytical,...,use,user,users,using,utilization,values,various,view,work,writing
0,,,,,,,,,,,,,,,,,,,,,
PO1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PO2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PO3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
PO4,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
PO5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
PO6,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,1,0,0,0
PO7,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
PO8,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PO9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
PO10,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
PO11,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
PO12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
PO13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
PO14,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
PO15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

## Intersection method for both CLOs and PLOs

### Generalised list of words

In [664]:
append_words = list(map(str.lower,["list", "recite", "outline", "define", "name", "match", "quote", "recall", "identify", "label", "recognize",
    "describe", "explain", "paraphrase", "restate", "give original examples of", "summarize", "contrast", "interpret", "discuss",
    "calculate", "predict", "apply", "solve", "illustrate", "use", "demonstrate", "determine", "model", "perform", "present",
    "classify", "break down", "categorize", "analyze", "diagram", "illustrate", "criticize", "simplify", "associate",
    "choose", "support", "relate", "determine", "defend", "judge", "grade", "compare", "contrast", "argue", "justify", "support", "convince", "select", "evaluate",
    "design", "formulate", "build", "invent", "create", "compose", "generate", "derive", "modify", "develop"]))

In [665]:
train_column = list(feature_names) + append_words

In [666]:
test_column = feature_names1

In [667]:
train_column = list(feature_names) + append_words # (PLO table ) (# using + operator to concat PLO words and list of generalized words)
test_column = feature_names1   # (CLO table)

In [668]:
common_column = list(set(train_column).intersection(set(test_column)))
common_column

['implement',
 'formulate',
 'systems',
 'use',
 'policies',
 'justify',
 'modify',
 'various',
 'effectively']

In [669]:
print(common_column)

['implement', 'formulate', 'systems', 'use', 'policies', 'justify', 'modify', 'various', 'effectively']

In [670]:
len(common_column)

9

In [671]:
U3 = U2.filter(list(common_column), axis=1)
U3

,implement,formulate,systems,use,policies,justify,modify,various,effectively
0,,,,,,,,,
CO1,0,0,0,0,0,1,0,1,0
CO2,0,1,1,1,1,0,0,0,0
CO3,0,0,1,0,0,0,0,0,1
CO4,1,0,0,0,0,0,1,0,0

In [672]:
Cs = []
for x in range(len(df)):
    Cs.append(U1.loc[['PO'+str(x+1)]])

In [673]:
Dds = []
for x in range(len(df)):
    Dds.append(pd.concat([Cs[x],U3], sort=True))

In [674]:
Ds = []
for x in range(len(df)):
    Ds.append(Dds[x].fillna(0))

## Calculate Cosine similarity

In [675]:
for x in range(len(df)):
    Dds[x] = pd.DataFrame(cosine_similarity(Ds[x], dense_output=True))

In [676]:
for x in range(len(df)):
    Dds[x].rename(columns = {0 :'PO'+str(x+1)}, inplace = True)

In [677]:
Ddn = []
for x in range(len(df)):
    Ddn.append(Dds[x]['PO'+str(x+1)])

d = pd.concat(Ddn, axis=1)

In [678]:
dd = d[1:]

In [679]:
dd.reset_index(inplace = True)
dd.drop(['index'], axis=1, inplace = True)

C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_528\2223456261.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd.drop(['index'], axis=1, inplace = True)

In [680]:

print(dd)

   PO1  PO2  PO3       PO4       PO5       PO6       PO7       PO8  PO9  \
0  0.0  0.0  0.0  0.000000  0.166667  0.204124  0.000000  0.000000  0.0
1  0.0  0.0  0.0  0.114708  0.117851  0.144338  0.109109  0.000000  0.0
2  0.0  0.0  0.0  0.324443  0.166667  0.204124  0.000000  0.144338  0.0
3  0.0  0.0  0.0  0.000000  0.166667  0.000000  0.000000  0.000000  0.0

       PO10      PO11  PO12  PO13  PO14  PO15
0  0.000000  0.000000   0.0   0.0   0.0   0.0
1  0.000000  0.000000   0.0   0.0   0.0   0.0
2  0.144338  0.000000   0.0   0.0   0.0   0.0
3  0.000000  0.119523   0.0   0.0   0.0   0.0

## Setting threshold value (taking min and max of each column and divided by 2)
## threshold value = (min +max)/2

In [681]:
for x in range(len(df)):
    tes = dd['PO'+str(x+1)].values.min()
    tes1 = dd['PO'+str(x+1)].values.max()
    tt1 = (tes+tes1)/2
    if tt1 == 0:
      dd['PO'+str(x+1)] = dd['PO'+str(x+1)] 
    else:
      dd['PO'+str(x+1)] = dd['PO'+str(x+1)].apply(lambda x: 1 if x >= tt1 else 0)

C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_528\2091158405.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd['PO'+str(x+1)] = dd['PO'+str(x+1)]
C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_528\2091158405.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd['PO'+str(x+1)] = dd['PO'+str(x+1)].apply(lambda x: 1 if x >= tt1 else 0)

In [682]:
dd

,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15
0,0.0,0.0,0.0,0,1,1,0,0,0.0,0,0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0,0,1,1,0,0.0,0,0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1,1,1,0,1,0.0,1,0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0,1,0,0,0,0.0,0,1,0.0,0.0,0.0,0.0

In [683]:
print(dd)

   PO1  PO2  PO3  PO4  PO5  PO6  PO7  PO8  PO9  PO10  PO11  PO12  PO13  PO14  \
0  0.0  0.0  0.0    0    1    1    0    0  0.0     0     0   0.0   0.0   0.0
1  0.0  0.0  0.0    0    0    1    1    0  0.0     0     0   0.0   0.0   0.0
2  0.0  0.0  0.0    1    1    1    0    1  0.0     1     0   0.0   0.0   0.0
3  0.0  0.0  0.0    0    1    0    0    0  0.0     0     1   0.0   0.0   0.0

   PO15
0   0.0
1   0.0
2   0.0
3   0.0

In [684]:
d.head()

,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15
0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.0,1.0,1.0,1.0
1,0.0,0.0,0.0,0.000000,0.166667,0.204124,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.114708,0.117851,0.144338,0.109109,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.324443,0.166667,0.204124,0.000000,0.144338,0.0,0.144338,0.000000,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.000000,0.166667,0.000000,0.000000,0.000000,0.0,0.000000,0.119523,0.0,0.0,0.0,0.0

In [685]:
d= pd.read_csv('CO-POMapping.csv')
d.head()

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15
0,CO1,Justify how resources will be allocated for th...,1,1,1,1,0,0,1,1,1,1,0,0,0,0,0
1,CO2,Formulate policies governing the use of IT Sys...,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0
2,CO3,Recommend measures on how to administer and ma...,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0
3,CO4,Modify configuration of an operating system to...,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0

In [686]:
df3 = d.copy()

In [687]:
df3

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15
0,CO1,Justify how resources will be allocated for th...,1,1,1,1,0,0,1,1,1,1,0,0,0,0,0
1,CO2,Formulate policies governing the use of IT Sys...,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0
2,CO3,Recommend measures on how to administer and ma...,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0
3,CO4,Modify configuration of an operating system to...,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0

In [688]:
for x in range(len(df)):
  df3['PO'+str(x+1)] = np.where(dd['PO'+str(x+1)] == df3['PO'+str(x+1)], 'True', 'False')

In [689]:
df3.head()

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15
0,CO1,Justify how resources will be allocated for th...,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True
1,CO2,Formulate policies governing the use of IT Sys...,False,False,False,True,False,True,True,False,False,False,True,True,True,True,True
2,CO3,Recommend measures on how to administer and ma...,False,False,True,True,True,True,False,True,False,True,False,False,False,True,True
3,CO4,Modify configuration of an operating system to...,False,False,False,False,True,False,False,False,False,False,True,False,False,True,True

In [690]:
for x in range(len(df)):
  df3['PO'+str(x+1)] = df3['PO'+str(x+1)].replace('True', 1)
  df3['PO'+str(x+1)] = df3['PO'+str(x+1)].replace('False', 0)

C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_528\1452448793.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3['PO'+str(x+1)] = df3['PO'+str(x+1)].replace('False', 0)
C:\Users\Jestoni Andales\AppData\Local\Temp\ipykernel_528\1452448793.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3['PO'+str(x+1)] = df3['PO'+str(x+1)].replace('True', 1)

In [691]:
df3['Average'] = df3.mean(axis=1, numeric_only=True)
df3.head()

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15,Average
0,CO1,Justify how resources will be allocated for th...,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0.333333
1,CO2,Formulate policies governing the use of IT Sys...,0,0,0,1,0,1,1,0,0,0,1,1,1,1,1,0.533333
2,CO3,Recommend measures on how to administer and ma...,0,0,1,1,1,1,0,1,0,1,0,0,0,1,1,0.533333
3,CO4,Modify configuration of an operating system to...,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0.266667

In [692]:
df4 = pd.concat([df1[0], df3], axis=1)
df4.head()

,0,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15,Average
0,CO1,CO1,Justify how resources will be allocated for th...,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0.333333
1,CO2,CO2,Formulate policies governing the use of IT Sys...,0,0,0,1,0,1,1,0,0,0,1,1,1,1,1,0.533333
2,CO3,CO3,Recommend measures on how to administer and ma...,0,0,1,1,1,1,0,1,0,1,0,0,0,1,1,0.533333
3,CO4,CO4,Modify configuration of an operating system to...,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0.266667

In [693]:
df4.set_index(0, inplace=True)
df4.head()

,CO,CO_Description,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15,Average
0,,,,,,,,,,,,,,,,,,
CO1,CO1,Justify how resources will be allocated for th...,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0.333333
CO2,CO2,Formulate policies governing the use of IT Sys...,0,0,0,1,0,1,1,0,0,0,1,1,1,1,1,0.533333
CO3,CO3,Recommend measures on how to administer and ma...,0,0,1,1,1,1,0,1,0,1,0,0,0,1,1,0.533333
CO4,CO4,Modify configuration of an operating system to...,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0.266667

In [694]:
df4['Average'].mean()

np.float64(0.41666666666666663)